AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple EC2 instance with Security Group'
Resources:
    MyEC2Instance:
        Type: 'AWS::EC2::Instance'
        Properties: 
            InstanceType: t2.micro
            ImageId: ami-0c55b159cbfafe1f0 # Replace with a valid AMI ID for your region
            KeyName: my-key-pair # Replace with your key pair name
            SecurityGroups:
                - !Ref MySecurityGroup

    MySecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            GroupDescription: Enable SSH access
            SecurityGroupIngress:
                - IpProtocol: tcp
                    FromPort: '22'
                    ToPort: '22'
                    CidrIp: 0.0.0.0/0